### ISSUE TITLE
Minimal size Docker image on JDK 8

### ISSUE THREAD

**Issue by srinivma1** [aws-samples/kubernetes-for-java-developers#25]
This is with reference to base docker image used for jdk 8 in the pom.xml for jib maven plugin(**openjdk:8-jre**).

After pushing the Spring boot image to docker registry using mvn comand, Spring boot application was found to be consuming **459 MB** size when I did a **docker pull** and queried it using **docker images** command.

For a customer who is still on JDK 8 and does not want to move to jdk 11, I would prefer to use **openjdk:8u171-alpine** base image. When I used the same code base which is mentioned in this git repository with **openjdk:8u171-alpine** as base image and deployed application, image size just came to **119 MB** which is a drastic improvement.

Just a note to reconsider this option as well.

**Comment by arun-gupta** [comment]
That is indeed a great observation. Do you want to send a PR?

**Comment by srinivma1** [comment]
Yes. I will raise pull request.

**Comment by arun-gupta** [comment]
Closed by https://github.com/aws-samples/kubernetes-for-java-developers/pull/26
