### ISSUE TITLE
eksctl path issue

### ISSUE THREAD

**Issue by shayarb** [aws-samples/kubernetes-for-java-developers#37]
Hi,
Please consider re-validate the command:
 
curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
 
seems like 'latest_release' path is no longer valid,
 
I temp workaround it using:
curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/0.1.29/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp

**Comment by arun-gupta** [comment]
This repo uses `brew install weaveworks/tap/eksctl` and refers to eksctl.io for other operating systems. Do you want to file an issue at https://github.com/weaveworks/eksctl/ instead?

**Comment by shayarb** [comment]
done:
https://github.com/aws-samples/eks-workshop/issues/334
